//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARIO
    {
        public string ID_BENEFICIARIO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string IP { get; set; }
        public string CODIGOCAE { get; set; }
    }
}
